name: DNSControl Preview

on:
  pull_request:
    branches: [master]

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  preview:
    name: Preview DNS changes
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download DNSControl binaries
        uses: actions/download-artifact@v3
        with:
          name: lib
          path: lib
      - name: Download compiled JS
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out
      - name: Make binaries executable
        run: chmod +x dnscontrol*
        working-directory: lib
        shell: bash
      - name: Pull CF secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.zhr.one
          role: dns
          path: github
          method: jwt
          jwtGithubAudience: sigstore
          secrets: |
            /ci-cd/dns CF_API
      - name: Generate and preview records
        run: ../lib/dnscontrol-Linux preview
        working-directory: out
        shell: bash
